# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2019

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'Get-AzResourcegroup'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
